### ISSUE TITLE
lampo-jsonrpc: do not returnt the errors back to the commands

### ISSUE THREAD

**Issue by vincenzopalazzo** [vincenzopalazzo/lampo.rs#174]
when I open a channel I get the following information in the log, but the command does not return any error response

```
2023-12-24T13:46:26.053Z DEBUG jsonrpc {"unnamed": [Response { result: Some(Object {"node_id": String("03cdc5ce9df1e05653a1f2db9e29bad1a1c81940315dd16e66216803aac07423aa"), "amount": Number(10000), "public": Bool(true), "push_mst": Number(0), "to_self_delay": Number(2016), "tx": Null}), error: None, id: Str("0"), jsonrpc: "2.0" }]}. [lampo-jsonrpc/src/lib.rs:149]
2023-12-24T13:46:26.067Z DEBUG ldk lightning::ln::peer_handler:1931 DEBUG Handling SendOpenChannel event in peer_handler for node 03cdc5ce9df1e05653a1f2db9e29bad1a1c81940315dd16e66216803aac07423aa for channel 90dfe394b6d67f6340a43452c10868860f239beb80ed0d4bf5717a0126b9747b. [lampod/src/utils/logger.rs:46]
2023-12-24T13:46:26.137Z DEBUG ldk lightning::ln::peer_handler:1600 DEBUG Got Err message from 03cdc5ce9df1e05653a1f2db9e29bad1a1c81940315dd16e66216803aac07423aa: Peer's feerate much too high. Actual: 1108. Our expected upper limit: 253. [lampod/src/utils/logger.rs:46]
2023-12-24T13:46:26.137Z ERROR ldk lightning::ln::channelmanager:2806 ERROR Force-closing channel 90dfe394b6d67f6340a43452c10868860f239beb80ed0d4bf5717a0126b9747b. [lampod/src/utils/logger.rs:49]
2023-12-24T13:46:26.137Z DEBUG ldk lightning::ln::channelmanager:2750 DEBUG Finishing force-closure of channel with 0 HTLCs to fail. [lampod/src/utils/logger.rs:46]
```

**Comment by tareknaser** [comment]
Here is an overview for what happens when a user calls `fundchannel`:
- We call [`create_channel()`](https://docs.rs/lightning/latest/lightning/ln/channelmanager/struct.ChannelManager.html#method.create_channel), which doesn't guarantee that the channel was funded. It just returns the channel's temporary  `channel_id`. If successful, we will receive `Event::FundingGenerationReady`
- When we receive `Event::FundingGenerationReady`, we create the funding transaction and call [`funding_transaction_generated()`](https://docs.rs/lightning/latest/lightning/ln/channelmanager/struct.ChannelManager.html#method.funding_transaction_generated). We also emit `LightningEvent::FundingChannelEnd`. The code I am referring to can be found here: https://github.com/vincenzopalazzo/lampo.rs/blob/main/lampod/src/actions/handler.rs#L163-L208

I also want to mention the response types we have for both `fundchannel` and `channels`:
- `fundchannel` returns a response of type `OpenChannel` which includes a field to hold the funding transaction.
- `channels` returns a response of type `Vec<Channel>` which doesn't contain the funding transaction. We are calling [`list_channels()`](https://docs.rs/lightning/latest/lightning/ln/channelmanager/struct.ChannelManager.html#method.list_channels) that returns a vector of `ChannelDetails` that contains `funding_txo` as a field but we don't collect this value and return it to the user. You can find relative code here: https://github.com/vincenzopalazzo/lampo.rs/blob/main/lampo-common/src/model/open_channel.rs

So I can think of two potential approaches:
- When a user calls `fundchannel`, we wait for `LightningEvent::FundingChannelEnd` to get the funding transaction and then return the response
- We contain the funding transaction as a field in the response of `channels` instead

**Comment by tareknaser** [comment]
Another aspect worth considering is the idea of waiting for events before returning from the `fundchannel` RPC call.

If we choose to wait for an event indicating that the funding transaction was broadcasted to the network, it would make sense to listen for other events as well, in cases of failure. 
For example, in [the logs of this issue](https://github.com/vincenzopalazzo/lampo.rs/issues/174#issue-2055106979), the channel was force closed due to "Peer's feerate much too high". If we only await success events, we will return a generic error message without specifying the reason for the failure. 

I think (and please correct me if I'm wrong) that the only way to provide a meaningful result for `fundchannel` within the current architecture is to listen for all possible events, whether they indicate success or failure.


  
I see two potential options:
1. Modify the current architecture:
    - Rename `fundchannel` to `openchannel`, as LDK's `channel_manager.open_channel()` doesn't guarantee successful channel creation.
    - Modify the response of `openchannel` so that it doesn't include the funding transaction, given that we don't know if the channel was successfully created.
    - Update the response of `channels` to include the funding transaction for each created channel. If the new channel doesn't exist in the list, this indicates a failed channel opening. Users can refer to the logs of `lampod-cli` for LDK events to know the reason of failure. 
2. Keep the current architecture of responses to RPC commands:
    - Listen for LDK events before returning from `fundchannel` RPC call
    -   If we receive an event indicating the broadcast of the funding transaction, we include it in the response before returning
    - Otherwise, if we receive an event indicating an error, we return the specific error that occurred

**Comment by vincenzopalazzo** [comment]
>If we choose to wait for an event indicating that the funding transaction was broadcasted to the network, it would make sense to listen for other events as well, in cases of failure.
For example, in https://github.com/vincenzopalazzo/lampo.rs/issues/174#issue-2055106979, the channel was force closed due to "Peer's feerate much too high". If we only await success events, we will return a generic error message without specifying the reason for the failure.

Yes it does, but a force close channel is completely irrelevant form the fundchannel operation, we need to just make sure that the transaction is sent correctly to the bitcoin network and at this point the job of the function transaction is finished.

The issue that you waiting pointing is another error that we should manage in another way.

>channels returns a response of type Vec<Channel> which doesn't contain the funding transaction. We are calling [list_channels()](https://docs.rs/lightning/latest/lightning/ln/channelmanager/struct.ChannelManager.html#method.list_channels) that returns a vector of ChannelDetails that contains funding_txo as a field but we don't collect this value and return it to the user. You can find relative code here: https://github.com/vincenzopalazzo/lampo.rs/blob/main/lampo-common/src/model/open_channel.rs

This is just an issue of our `chanenls` method, there is nothing to do with this issue

>I see two potential options:

Point two is the correct one, but you are complicating too much, for now, we just need to wait for a funding transaction is propagate and start experimenting with it, overdesign is a killer.

This solution that you are proposing need to be propose as a second PR and you need to prove that your approach works, because currently I have no idea that your idea works with the big delay of the mainet, maybe with the toy network yes, but with the bitcoin network I am not sure
